from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class Item(BaseModel):
    id: int
    name: str
    price: int
    category: str
    description: str
    attackDamage: Optional[float] = 0
    abilityPower: Optional[float] = 0
    attackSpeed: Optional[float] = 0
    health: Optional[float] = 0
    mana: Optional[float] = 0
    armor: Optional[float] = 0
    magicResist: Optional[float] = 0
    critChance: Optional[float] = 0
    abilityHaste: Optional[float] = 0
    movementSpeed: Optional[float] = 0
    lifeSteal: Optional[float] = 0
    armorPenetration: Optional[float] = 0
    magicPenetration: Optional[float] = 0
    tenacity: Optional[float] = 0

items = [
    {
        "id": 1,
        "name": "Doran's Blade",
        "price": 450,
        "category": "Starter items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1055.png",
        "attackDamage": 10,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 80,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 3.5,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Good starter item for physical damage champions."
    },
    {
        "id": 2,
        "name": "Health Potion",
        "price": 50,
        "category": "Consumable items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/2003.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Consumes the potion to restore 120 Health over 15 seconds."
    },
    {
        "id": 3,
        "name": "Long Sword",
        "price": 350,
        "category": "Basic items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1036.png",
        "attackDamage": 10,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Basic component item providing raw Attack Damage."
    },
    {
        "id": 4,
        "name": "Boots of Speed",
        "price": 300,
        "category": "Boot",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1001.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 25,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Enhances Movement Speed."
    },
    {
        "id": 5,
        "name": "B. F. Sword",
        "price": 1300,
        "category": "Basic items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1038.png",
        "attackDamage": 40,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Powerful component item required for high-tier physical damage weapons."
    },
    {
        "id": 6,
        "name": "Infinity Edge",
        "price": 3400,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3031.png",
        "attackDamage": 80,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 25,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Massively boosts attack damage and critical strike damage."
    },
    {
        "id": 7,
        "name": "Bloodthirster",
        "price": 3400,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3072.png",
        "attackDamage": 80,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 18,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants high attack damage, lifesteal, and a shield at full health."
    },
    {
        "id": 8,
        "name": "Rabadon's Deathcap",
        "price": 3600,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3089.png",
        "attackDamage": 0,
        "abilityPower": 140,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Increases total Ability Power by 35%."
    },
    {
        "id": 9,
        "name": "Guardian Angel",
        "price": 3200,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3026.png",
        "attackDamage": 55,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 45,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Revives user upon taking fatal damage."
    },
    {
        "id": 10,
        "name": "Trinity Force",
        "price": 3333,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3078.png",
        "attackDamage": 45,
        "abilityPower": 0,
        "attackSpeed": 33,
        "health": 300,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 20,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Empowers auto-attacks after casting abilities."
    },
    {
        "id": 11,
        "name": "Zhonya's Hourglass",
        "price": 3250,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3157.png",
        "attackDamage": 0,
        "abilityPower": 120,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 50,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Puts user in Stasis for 2.5 seconds, becoming invulnerable."
    },
    {
        "id": 12,
        "name": "Kraken Slayer",
        "price": 3100,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/6672.png",
        "attackDamage": 50,
        "abilityPower": 0,
        "attackSpeed": 40,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 7,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Deals bonus damage on every third auto-attack."
    },
    {
        "id": 13,
        "name": "Shadowflame",
        "price": 3200,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/4645.png",
        "attackDamage": 0,
        "abilityPower": 115,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 12,
        "tenacity": 0,
        "description": "Magic damage and damage over time critically strike low-health enemies."
    },
    {
        "id": 14,
        "name": "Sterak's Gage",
        "price": 3200,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3053.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 400,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 20,
        "description": "Grants bonus AD based on base AD and a huge shield when low health."
    },
    {
        "id": 15,
        "name": "Thornmail",
        "price": 2700,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3075.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 350,
        "mana": 0,
        "armor": 70,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Reflects magic damage back to attackers and applies Grievous Wounds."
    },
    {
        "id": 16,
        "name": "Bork (Blade of the Ruined King)",
        "price": 3200,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3153.png",
        "attackDamage": 50,
        "abilityPower": 0,
        "attackSpeed": 25,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 10,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "On-hit attacks deal current health percent damage and steal movement speed."
    },
    {
        "id": 17,
        "name": "Lich Bane",
        "price": 3100,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3100.png",
        "attackDamage": 0,
        "abilityPower": 100,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 15,
        "movementSpeed": 8,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "After casting an ability, your next auto-attack deals bonus AP damage."
    },
    {
        "id": 18,
        "name": "Lord Dominik's Regards",
        "price": 3000,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3036.png",
        "attackDamage": 45,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 25,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 40,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Provides armor penetration against high-armor targets."
    },
    {
        "id": 19,
        "name": "Jak'Sho, The Protean",
        "price": 3200,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/6665.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 300,
        "mana": 0,
        "armor": 50,
        "magicResist": 50,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Gains increasing Armor and Magic Resist while in combat with champions."
    },
    {
        "id": 20,
        "name": "Luden's Companion",
        "price": 3000,
        "category": "Legendary items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/6655.png",
        "attackDamage": 0,
        "abilityPower": 90,
        "attackSpeed": 0,
        "health": 0,
        "mana": 600,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 20,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Fires charges at targets upon dealing ability damage."
    },
    {
        "id": 21,
        "name": "Berserker's Greaves",
        "price": 1100,
        "category": "Boots",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3006.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 35,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Enhanced Movement Speed and Attack Speed."
    },
    {
        "id": 22,
        "name": "Boots of Swiftness",
        "price": 900,
        "category": "Boots",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3009.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 60,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Reduces the effectiveness of slow effects on your champion."
    },
    {
        "id": 23,
        "name": "Ionian Boots of Lucidity",
        "price": 900,
        "category": "Boots",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3158.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 15,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Reduces Summoner Spell cooldowns and grants Ability Haste."
    },
    {
        "id": 24,
        "name": "Mercury's Treads",
        "price": 1100,
        "category": "Boots",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3111.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 25,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 30,
        "description": "Grants Magic Resist and Tenacity, reducing the duration of stuns, slows, and other crowd control."
    },
    {
        "id": 25,
        "name": "Plated Steelcaps",
        "price": 1100,
        "category": "Boots",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3047.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 20,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Reduces incoming damage from basic attacks."
    },
    {
        "id": 26,
        "name": "Sorcerer's Shoes",
        "price": 1100,
        "category": "Boots",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/3020.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 18,
        "tenacity": 0,
        "description": "Grants Magic Penetration to pierce through enemy resistances."
    },
    {
        "id": 27,
        "name": "Armored Advance",
        "price": 1100,
        "category": "Boots",
        "image": "https://wiki.leagueoflegends.com/en-us/images/Armored_Advance_item.png?3d928",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 30,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants enhanced armor and mobility."
    },
    {
        "id": 28,
        "name": "Chainlaced Crushers",
        "price": 1100,
        "category": "Boots",
        "image": "https://wiki.leagueoflegends.com/en-us/images/Chainlaced_Crushers_item.png?c0063",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 25,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 30,
        "description": "Grants magic resistance and movement speed."
    },
    {
        "id": 29,
        "name": "Crimson Lucidity",
        "price": 900,
        "category": "Boots",
        "image": "https://wiki.leagueoflegends.com/en-us/images/Crimson_Lucidity_item.png?ff157",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 15,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants ability haste and movement speed."
    },
    {
        "id": 30,
        "name": "Gluttonous Greaves",
        "price": 1000,
        "category": "Boots",
        "image": "https://wiki.leagueoflegends.com/en-us/images/Gluttonous_Greaves_item.png?d560e",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants lifesteal and movement speed."
    },
    {
        "id": 31,
        "name": "Gunmetal Greaves",
        "price": 1100,
        "category": "Boots",
        "image": "https://wiki.leagueoflegends.com/en-us/images/Gunmetal_Greaves_item.png?f5849",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 25,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants attack speed and movement speed."
    },
    {
        "id": 32,
        "name": "Immortal Path",
        "price": 1100,
        "category": "Boots",
        "image": "https://wiki.leagueoflegends.com/en-us/images/Immortal_Path_item.png?c2e5b",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 150,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants health and enhanced mobility."
    },
    {
        "id": 33,
        "name": "Spellslinger's Shoes",
        "price": 1100,
        "category": "Boots",
        "image": "https://wiki.leagueoflegends.com/en-us/images/Spellslinger%27s_Shoes_item.png?34992",
        "attackDamage": 0,
        "abilityPower": 30,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 45,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants ability power and movement speed."
    },
    {
        "id": 34,
        "name": "Swiftmarch",
        "price": 1000,
        "category": "Boots",
        "image": "https://wiki.leagueoflegends.com/en-us/images/Swiftmarch_item.png?50274",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 65,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants superior raw movement speed."
    },
    {
        "id": 35,
        "name": "Slightly Magical Boots",
        "price": 0,
        "category": "Boots",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/2422.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 25,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Slightly more magical than standard boots. Grants a minor movement speed boost."
    },
    {
        "id": 36,
        "name": "Amplifying Tome",
        "price": 400,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1052.png",
        "attackDamage": 0,
        "abilityPower": 20,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants ability power."
    },
    {
        "id": 37,
        "name": "Blasting Wand",
        "price": 850,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1026.png",
        "attackDamage": 0,
        "abilityPower": 45,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants moderate ability power."
    },
    {
        "id": 38,
        "name": "Cloak of Agility",
        "price": 600,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1018.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 15,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants critical strike chance."
    },
    {
        "id": 39,
        "name": "Cloth Armor",
        "price": 300,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1029.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 15,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants armor."
    },
    {
        "id": 40,
        "name": "Dagger",
        "price": 300,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1042.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 12,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants attack speed."
    },
    {
        "id": 41,
        "name": "Faerie Charm",
        "price": 250,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1004.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Improves mana regeneration."
    },
    {
        "id": 42,
        "name": "Glowing Mote",
        "price": 250,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/2022.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 5,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants ability haste."
    },
    {
        "id": 43,
        "name": "Needlessly Large Rod",
        "price": 1250,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1058.png",
        "attackDamage": 0,
        "abilityPower": 65,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants a large amount of ability power."
    },
    {
        "id": 44,
        "name": "Null-Magic Mantle",
        "price": 450,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1033.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 25,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants magic resistance."
    },
    {
        "id": 45,
        "name": "Pickaxe",
        "price": 875,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1037.png",
        "attackDamage": 25,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants attack damage."
    },
    {
        "id": 46,
        "name": "Rejuvenation Bead",
        "price": 300,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1006.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Improves health regeneration."
    },
    {
        "id": 47,
        "name": "Ruby Crystal",
        "price": 400,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1028.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 150,
        "mana": 0,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants health."
    },
    {
        "id": 48,
        "name": "Sapphire Crystal",
        "price": 350,
        "category": "Basic Items",
        "image": "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/item/1027.png",
        "attackDamage": 0,
        "abilityPower": 0,
        "attackSpeed": 0,
        "health": 0,
        "mana": 250,
        "armor": 0,
        "magicResist": 0,
        "critChance": 0,
        "abilityHaste": 0,
        "movementSpeed": 0,
        "lifeSteal": 0,
        "armorPenetration": 0,
        "magicPenetration": 0,
        "tenacity": 0,
        "description": "Grants mana."
    }

]


@app.get("/items")
def get_items():
    return {"items": items}


@app.get("/items/search")
def search_items(q: Optional[str] = None):
    if not q:
        return {"results": items}
    filtered = [item for item in items if q.lower() in item["name"].lower()]
    return {"results": filtered}

@app.get("/items/{item_id}")
def get_item(item_id: int):
    for item in items:
        if item["id"] == item_id:
            return item
    return {"error": "Item not found"}
